### ISSUE TITLE
`python setup.py update` no longer works

### ISSUE THREAD

**Issue by sebastinas** [jquast/wcwidth#17]
On a fresh checkout:
```
$ python3 setup.py update
running update
data/ created.
retrieving http://www.unicode.org/Public/UNIDATA/EastAsianWidth.txt.
data/EastAsianWidth.txt saved.
parsing data/EastAsianWidth.txt ..
Traceback (most recent call last):
  File "setup.py", line 252, in <module>
    main()
  File "setup.py", line 248, in main
    cmdclass={'update': SetupUpdate},
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 64, in run
    self.do_east_asian()
  File "setup.py", line 72, in do_east_asian
    properties=(u'W', u'F',)
  File "setup.py", line 127, in _parse_east_asian
    uline = line.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2: ordinal not in range(128)
```

**Comment by jquast** [comment]
Thank you @sebastinas I'll look at it within 24 hours.

**Comment by sebastinas** [comment]
Thank you, with 81db49a it works again.

**Comment by jquast** [comment]
Release ``wcwidth==0.1.7`` on pypi with this fix. Thanks again for filing the issue. Tables were updated to Unicode specification 9.0.0 in this release.

I did not make note of this bug in the changelog, because the ``setup.py update`` entrypoint it is not distributed, only meant to be used upstream (here). If the tables become out of date, please file an issue/PR, I'll release a new one.

As a library for developers, anyway, you are welcome to use it in any process, and we'll try to keep this "setup.py update" entrypoint for as long as python supports it.

Please enjoy!
