### ISSUE TITLE
some emojis return width of 1

### ISSUE THREAD

**Issue by st-pasha** [jquast/wcwidth#27]
This is something that I've been struggling with. Consider the following example:
```
>>> print('\U0001f6cd')
🛍
>>> wcwidth.wcwidth('\U0001f6cd')
1
```
In this case the display width of the symbol is 2 (as I believe is appropriate per Unicode standard). What is annoying though is that the terminal (default terminal on MacOS 10.13, with the default font SF Mono Regular) also thinks that the character has width 1, and draws the following character on top of this emoji.

I wonder if it is possible to create a special "print" method that knows to insert a superficial space after characters like this, ensuring that the output in terminal is not buggy?

**Comment by jquast** [comment]
We use an automatic process to gather the values from the unicode specification files released, (bin/update-tables.py), maybe we just need to run them again, we also support choosing the version in this PR, https://github.com/jquast/wcwidth/pull/23 so we can compare different values.

The real problem is your Terminal.app, or iTerm2.app in my case, they have their own implementation of wcwidth(), the one that comes with the system library, and better terminal emulators start rolling their own, more up-to-date version

**Comment by jquast** [comment]
@st-pasha if you are still interested in this issue, it may be a problem with the Unicode Consortium's definition. This is defined as a width of `1` for *all* versions of Unicode Specification.

And in my Terminal, iTerm2.app, which is based on version 12.0.0, it is indeed printed as a single-wide character, which is seen easily by putting `|` around the character:

<img width="412" alt="Screen Shot 2020-06-01 at 1 20 03 PM" src="https://user-images.githubusercontent.com/972584/83435661-9c789d80-a40a-11ea-9461-6949749e4486.png">

This is where you can report this issue: https://corp.unicode.org/reporting.html
